### ISSUE TITLE
[bug report] functionality conflict with other WX

### ISSUE THREAD

**Issue by n8v8R** [mozfreddyb/webext-firstpartyisolation#10] opened 2018-10-26 05:22 UTC
Suppose this is independent of OS (version) but it should be mentioned that this is reported from a W10 x64 v1809 b17763.55 and FF 65.0a1 (2018-10-25) (64-bit) and v1.3.1 of this WX

**Comment by mozfreddyb** [comment] 2018-10-26 08:58
Thank you for trying my extension.
It does works for me on Nightly. So, please help me understand what exactly isn't working for you.
Can you provide a detailed explanation containing three items: 1) Steps To Repeat, 2) What you expected to happen and 3) What actually happened

Otherwise, I will have to close this issue as invalid.

**Comment by n8v8R** [comment] 2018-10-26 09:30
I would expect clicking ther WE's icon in order to disable/enable FPI the value of `privacy.firstparty.isolate` being toggled accordingly (false/true). But that is not happening.

![fip disabled](https://user-images.githubusercontent.com/13611490/47558036-b7675f80-d901-11e8-9917-bdb2ebbcc337.png)

**Comment by mozfreddyb** [comment] 2018-10-26 09:43
This is odd. I can't reproduce on Firefox Nightly 65.0a1 (2018-10-25) (64-bit).

What I'm doing:
1) go to about:config, search for isolate
2) Click the fishbowl
3) Turns orange and pref gets set to `false`.
4) Click again
4) Turns grey and pref gets set to `true` again.

Can you try again with all of your other extensions disabled? The button "Restart with add-ons disabled" in `about:support` is useful here

**Comment by n8v8R** [comment] 2018-10-26 10:04
> What I'm doing:

Same this end but different outcome.

> all of your other extensions disabled? The button "Restart with add-ons disabled" in `about:support` is useful here

It is not really, because it restarts the browser in safe mode and prevents, like any other WX, from being enabled.

So probably a conflict with (an)other WX(s) then. Thus far discovered the settings of those taking precedence (toggling their FPI settings toggles also `privacy.firstparty.isolate`) over this WX.

- https://addons.mozilla.org/en-GB/firefox/addon/privacy-guard-manager
- https://addons.mozilla.org/en-GB/firefox/addon/chameleon-ext

Disabling those WX returns the functionality of this WX

**Comment by n8v8R** [comment] 2018-10-26 10:49
> I don't understand why you have many extensions providing the same functionality.

This WX been used to toggle FPI quickly if needed and to indicate the current status of FPI, as it only serves/focuses on FPI. Other WX have extended functionality beyond FPI but FPI cannot be toggled with a single click on the WX icon and lacking a status indicator of the FPI status.

> If you have another extension enforcing the pref to be set, we can't do our thing reliably.

I am not a coder and a have no clue how Mozialla has designed/implemented WX to interact with each other in terms of seizing control of a config setting, i.e. whether only a single WX can be in control of a config exclusively and how the order of control is established.
I would have assumed that WX are treated equally and a config setting changed via one WX is reflected in the settings of the other WX (and vice versa).

My understanding now is that this WX assumes to be the sole WX in control of FPI and is currently not checking/reading/reflecting the actual status of `privacy.firstparty.isolate`.

It would be good if this WX would not ony reflect the actual status of FPI (icon colour) but somehow also be able to change the FPI status even if another WX is offering the same option.

> I'd lean towards closing this as a "bug report"

You are the developer and thus at liberty. I just reported the issue encountered. For the time being I have disabled this WX for the apparent reason.

**Comment by mozfreddyb** [comment] 2018-10-29 09:30
> My understanding now is that this WX assumes to be the sole WX in control of FPI and is currently not checking/reading/reflecting the actual status of privacy.firstparty.isolate.

Yes. I will fix that in #11.

> It would be good if this WX would not ony reflect the actual status of FPI (icon colour) but somehow also be able to change the FPI status even if another WX is offering the same option.

With FPI enabled, the button will continue to work as a toggle. With one caveat:
But if another web extension monitors for changes of the pref and re-enables it, then this extensions won't be able to overpower the misbehaving extension. At that point, you'll have to decide.

**Closed** 2018-10-29 09:43 UTC
Labels: incomplete
